# permissions for end users to edit learns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: learn-editor-role
rules:
- apiGroups:
  - tg.my.domain
  resources:
  - learns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tg.my.domain
  resources:
  - learns/status
  verbs:
  - get
